-- White Box Autonomy — Observatory editorial seed (the nine curated records).
--
-- WHAT THIS IS
--   A mechanical, reviewable transcription of src/lib/events/data/seed.ts into
--   the `event` / `event_source` tables created by
--   supabase/migrations/20260829235332_observatory_core.sql. Every editorial
--   value below is copied verbatim from seed.ts.
--
-- WHAT THIS IS NOT
--   Not a schema migration. It is editorial content, not DDL history, so it
--   lives here (not in supabase/migrations/) and is never applied by
--   `supabase db push`. Re-running it re-syncs data; a migration would not.
--
-- HOW TO RUN IT
--   Against the linked hosted project — uses the CLI's stored `supabase login`
--   token via the Management API; no database password or service-role key:
--
--       npx supabase db query --linked --file supabase/seed.sql
--
--   It is also loaded automatically into a LOCAL database by `supabase db
--   reset` (config.toml -> [db.seed]). `db reset` never touches the hosted DB.
--
-- PUBLICATION PATH
--   Events are upserted as DRAFTS (is_public is not carried by the upsert at
--   all), then their sources are upserted, then a final `UPDATE ... SET
--   is_public = true` publishes the nine records. This is the one canonical
--   publication path enforced by the database
--   (20260901000000_public_event_requires_source.sql): is_public can only go
--   not-true -> true via an UPDATE, and only once >= 1 source exists. The seed
--   uses the same path as the application.
--
-- IDEMPOTENCY
--   Each row is an upsert keyed by its natural identifier — `event.slug` and
--   `event_source (event_id, url)`. The `DO UPDATE` carries a
--   `WHERE ... IS DISTINCT FROM ...` guard over every editorial column, so:
--     * first run           -> INSERT drafts; then the publish UPDATE stamps
--                              first_published_at once (via the lifecycle
--                              trigger) and sets is_public = true.
--     * re-run, no changes  -> the editorial guard is false for every row, so
--                              NO editorial UPDATE executes; the publish UPDATE
--                              carries `AND is_public IS NOT TRUE`, so it also
--                              matches nothing and first_published_at is never
--                              re-stamped. updated_at is left untouched.
--     * re-run after an edit -> only the changed rows UPDATE, and only those
--                              rows receive a new updated_at.
--   `id` is left to the column default gen_random_uuid(); `slug` is the stable
--   public identifier. `created_at` / `updated_at` / `first_published_at` are
--   never written explicitly here.
--
-- Source of truth: seed.ts, RECORD_UPDATED = 2026-08-30.

begin;

-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
with seed (
  slug, title, summary, occurred_on, occurred_on_precision,
  location_text, location_country_code, developer_or_operator, system_name,
  automation_status, system_version, system_version_knowledge,
  event_type, valence, observed_facts, unknowns, interpretation,
  causation_status, causation_note, review_status, record_updated
) as (
  values

  -- 1. fsd-slows-for-crossing-pedestrian-then-resumes
  (
    $$fsd-slows-for-crossing-pedestrian-then-resumes$$,
    $$FSD slows for a crossing pedestrian, then resumes as the pedestrian stops$$,
    $$With FSD (Supervised) engaged, the vehicle slowed as a pedestrian ran across its path and resumed acceleration shortly after the pedestrian stopped part-way across.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$vulnerable-road-user-interaction$$, $$successful-handling$$,
    array[
      $$FSD (Supervised) was engaged during the interaction.$$,
      $$A pedestrian ran across the vehicle's path.$$,
      $$The vehicle slowed while the pedestrian was crossing.$$,
      $$The pedestrian stopped before completing the crossing.$$,
      $$The vehicle resumed acceleration shortly after the pedestrian stopped.$$,
      $$No collision occurred in the recorded interaction.$$
    ],
    array[
      $$What cues the automation used in responding to the pedestrian.$$,
      $$Whether the system predicted that the pedestrian would stop, or reacted after detecting the reduction in pedestrian movement.$$,
      $$The internal pedestrian trajectory or prediction generated by the system.$$
    ],
    $$The rapid transition from yielding to resuming movement is consistent with an effective response to the pedestrian's changing behaviour. The external video evidence alone cannot establish whether the system anticipated the pedestrian's intention or reacted after detecting the pedestrian stopping.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 2. fsd-remains-stopped-in-car-park-then-hesitates
  (
    $$fsd-remains-stopped-in-car-park-then-hesitates$$,
    $$FSD remains stopped as another vehicle passes in a car park, then hesitates during a right-of-way interaction$$,
    $$With FSD (Supervised) engaged in a busy car park, the vehicle stayed stopped while another vehicle passed through the area ahead of its intended path. Shortly afterwards it hesitated during an interaction with an oncoming vehicle that was indicating a turn, and the other driver waved it through.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$unexpected-or-inappropriate-behaviour$$, $$neutral-or-unclear$$,
    array[
      $$FSD (Supervised) was activated in a busy car park.$$,
      $$The vehicle initially did not proceed with the intended manoeuvre.$$,
      $$Another vehicle passed through the area ahead of the vehicle's intended path.$$,
      $$The vehicle remained stationary while that other vehicle passed.$$,
      $$Shortly afterwards the vehicle stopped or hesitated during an interaction with an oncoming vehicle that was indicating a right turn.$$,
      $$The other driver then used a hand gesture indicating that the vehicle could proceed.$$
    ],
    array[
      $$Which objects or predicted trajectories caused the initial stationary behaviour.$$,
      $$Whether the passing vehicle was the primary reason the system did not proceed.$$,
      $$Why the system hesitated during the second interaction.$$,
      $$How the system interpreted the other vehicle's indicator.$$,
      $$Whether or how the hand gesture influenced subsequent behaviour.$$,
      $$Whether the system explicitly represented right of way.$$
    ],
    $$The first interaction is consistent with cautious and potentially beneficial conflict avoidance: proceeding could have created a conflict with the passing vehicle. The second interaction suggests greater difficulty resolving an ambiguous social negotiation involving an indicator, right of way and a driver's hand gesture. The available external evidence does not reveal the system's internal reasoning.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 3. fsd-repeated-lateral-weaving
  (
    $$fsd-repeated-lateral-weaving$$,
    $$FSD exhibits repeated lateral weaving during automated driving$$,
    $$On the first day of using a newly updated version of Tesla FSD (Supervised), with automation engaged, the vehicle moved from side to side repeatedly over a short period in a way inconsistent with holding a stable path.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$near-miss-or-safety-critical$$, $$failure-or-challenging$$,
    array[
      $$The event occurred during the first day of using a newly updated version of Tesla FSD (Supervised).$$,
      $$Driving automation was engaged.$$,
      $$The vehicle moved laterally from side to side.$$,
      $$The lateral movement repeated during a short period.$$,
      $$The behaviour was inconsistent with maintaining a stable roadway path.$$,
      $$No collision occurred in the recorded event.$$
    ],
    array[
      $$The perception, localisation, planning or control process associated with the oscillation.$$,
      $$Whether road geometry, lane markings, localisation, surrounding traffic or other environmental conditions contributed.$$,
      $$Whether the behaviour would have continued without intervention.$$,
      $$The exact lateral displacement and safety margin.$$,
      $$The exact software version in use.$$
    ],
    $$The repeated lateral movement is consistent with unstable or inappropriate path control during automated driving. The available video can document the observable weaving, but it cannot establish which subsystem or environmental factor caused the behaviour.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 4. fsd-right-turn-from-left-turn-only-lane
  (
    $$fsd-right-turn-from-left-turn-only-lane$$,
    $$FSD attempts a right turn from a left-turn-only lane$$,
    $$With FSD (Supervised) engaged while the vehicle was in a lane marked for left turns only, the system began a right-turn manoeuvre from that lane while traffic was moving in the target direction. The driver intervened before the manoeuvre was completed.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$traffic-rule-or-infrastructure-interpretation$$, $$failure-or-challenging$$,
    array[
      $$The vehicle was travelling in a lane designated for left turns only.$$,
      $$With FSD (Supervised) engaged, the vehicle initiated or attempted a right-turn manoeuvre from that lane.$$,
      $$Moving traffic was present in the direction of the attempted manoeuvre.$$,
      $$The driver intervened before the manoeuvre was completed.$$,
      $$No collision occurred.$$
    ],
    array[
      $$Whether the lane-use restriction was perceived correctly.$$,
      $$Whether road geometry, map information, lane markings or route guidance contributed.$$,
      $$Whether the intended navigation route required a right turn.$$,
      $$The exact time-to-collision or remaining safety margin.$$,
      $$What trajectory the vehicle would ultimately have followed without intervention.$$
    ],
    $$The event is consistent with an inappropriate manoeuvre selection relative to the marked lane-use restriction. The intervention prevented the attempted turn from progressing into moving traffic. The available video does not establish whether the underlying cause involved lane perception, map interpretation, route planning or another component of the driving-automation system.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 5. fsd-does-not-yield-to-ambulance-before-intervention
  (
    $$fsd-does-not-yield-to-ambulance-before-intervention$$,
    $$FSD does not yield to an ambulance before driver intervention$$,
    $$With FSD (Supervised) engaged, the vehicle did not perform the yielding response the driver judged necessary while an ambulance was present in surrounding traffic, and the driver took over control.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$emergency-vehicle-interaction$$, $$failure-or-challenging$$,
    array[
      $$An ambulance was present in the surrounding traffic environment.$$,
      $$FSD (Supervised) was engaged during the interaction.$$,
      $$Before driver intervention, the vehicle did not exhibit the yielding response the driver considered necessary.$$,
      $$The driver intervened and took control.$$,
      $$No collision occurred.$$
    ],
    array[
      $$Whether the system detected and correctly classified the ambulance.$$,
      $$Whether emergency lights or a siren were active and clearly detectable from the evidence.$$,
      $$Whether the system recognised a requirement to yield.$$,
      $$What trajectory or behavioural prediction the system generated for the ambulance.$$,
      $$Whether the system would eventually have yielded without intervention.$$
    ],
    $$The event is consistent with an inadequate response to an emergency vehicle while driving automation was engaged. The available evidence establishes the externally observable behaviour and the driver intervention, but does not determine whether the limitation arose from perception, classification, behavioural prediction, right-of-way reasoning or motion planning.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 6. fsd-course-change-within-intersection
  (
    $$fsd-course-change-within-intersection$$,
    $$FSD changes course within an intersection toward a red signal$$,
    $$While traversing an intersection with FSD (Supervised) engaged, the vehicle changed its path or heading, and the revised trajectory moved toward a direction associated with a red traffic signal so far as the recording shows.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$traffic-rule-or-infrastructure-interpretation$$, $$failure-or-challenging$$,
    array[
      $$The vehicle entered or was travelling through an intersection with FSD (Supervised) engaged.$$,
      $$While within the intersection, the vehicle changed its path or heading.$$,
      $$The revised trajectory took the vehicle toward a movement associated with a red traffic signal, so far as is clearly visible from the evidence.$$,
      $$The behaviour prompted driver concern.$$,
      $$No collision occurred in the recorded event.$$
    ],
    array[
      $$Whether lane geometry, turn-path interpretation, lane assignment, route guidance or traffic-signal association contributed.$$,
      $$Whether the visible red signal definitively applied to the trajectory the system was attempting to follow.$$,
      $$The path the vehicle would ultimately have followed without intervention.$$,
      $$Whether map data, perception, localisation or planning contributed.$$,
      $$Whether and when the driver intervened.$$
    ],
    $$The event is consistent with an inappropriate change in planned trajectory while traversing an intersection. The resulting path appeared to align with a movement controlled by a red signal. The available external evidence does not reveal whether the underlying issue arose from lane interpretation, signal association, localisation, route planning or another component.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 7. fsd-road-markings-low-traffic-street
  (
    $$fsd-road-markings-low-traffic-street$$,
    $$FSD does not follow road markings on a low-traffic street$$,
    $$At around 4 a.m. on a street with little or no visible traffic, with FSD (Supervised) engaged, the vehicle's path did not consistently follow the visible road markings and lane layout.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$traffic-rule-or-infrastructure-interpretation$$, $$failure-or-challenging$$,
    array[
      $$The event occurred at approximately 4 a.m.$$,
      $$Traffic was very light or absent in the visible scene.$$,
      $$Road markings were present.$$,
      $$With FSD (Supervised) engaged, the vehicle did not consistently follow the marked roadway or lane guidance.$$,
      $$The vehicle's path was inconsistent with the expected movement indicated by the visible road markings and traffic-control layout.$$,
      $$No collision occurred.$$
    ],
    array[
      $$Whether the road markings were perceived correctly.$$,
      $$Whether map information or route guidance conflicted with the physical road layout.$$,
      $$Whether lighting, road-surface condition or marking quality influenced the behaviour.$$,
      $$Whether perception, localisation, planning or another component contributed.$$,
      $$Whether the same behaviour would occur during daylight or in heavier traffic.$$,
      $$Which specific road rules, if any, were breached.$$
    ],
    $$The event is consistent with a failure to interpret or comply with visible roadway guidance in a low-traffic environment. The relatively simple surrounding traffic conditions make the behaviour noteworthy, but the external video alone cannot establish why the system selected that path.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 8. fsd-standing-water-stormy-night
  (
    $$fsd-standing-water-stormy-night$$,
    $$FSD drives through substantial standing water at night in stormy conditions$$,
    $$At night in stormy conditions, with FSD (Supervised) engaged, the vehicle continued into a large area of standing water on the roadway and produced a substantial splash while passing through it.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$unexpected-or-inappropriate-behaviour$$, $$failure-or-challenging$$,
    array[
      $$The event occurred at night during stormy or heavy-rain conditions.$$,
      $$A substantial area of standing water was visible on the roadway.$$,
      $$With FSD (Supervised) engaged, the vehicle continued into the standing water.$$,
      $$The vehicle produced a substantial splash while passing through it.$$,
      $$No collision occurred in the recorded event.$$
    ],
    array[
      $$The depth of the standing water.$$,
      $$Whether the system detected the water as a distinct roadway hazard.$$,
      $$Whether the vehicle modified its speed before entering the water.$$,
      $$Whether the roadway remained safely passable.$$,
      $$Whether visibility, reflections, rainfall or sensor performance influenced the behaviour.$$,
      $$What the system would have done if the water had been deeper or impassable.$$
    ],
    $$The event shows the driving-automation system proceeding through substantial standing water under degraded nighttime weather conditions. The available video establishes the observable vehicle behaviour, but not whether the system recognised the water as a hazard or how it assessed its depth and passability.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  ),

  -- 9. fsd-railway-crossing-hard-braking
  (
    $$fsd-railway-crossing-hard-braking$$,
    $$FSD proceeds toward a railway crossing before a hard braking intervention$$,
    $$With FSD (Supervised) engaged, the vehicle continued forward in a railway-crossing environment to a point where track clearance became a concern to the driver, who applied a hard braking input strong enough to displace unsecured objects in the vehicle.$$,
    null, $$unknown$$,
    null, null, $$Tesla$$, $$FSD (Supervised)$$,
    $$driving-automation-engaged-confirmed$$, null, $$unknown$$,
    $$traffic-rule-or-infrastructure-interpretation$$, $$failure-or-challenging$$,
    array[
      $$The vehicle approached or entered a railway-crossing environment with FSD (Supervised) engaged.$$,
      $$The vehicle continued forward into a situation where railway-track clearance became a concern to the driver.$$,
      $$The driver applied a hard braking intervention.$$,
      $$The braking was forceful enough that unsecured objects inside the vehicle moved substantially.$$,
      $$No collision occurred.$$
    ],
    array[
      $$Whether the system correctly identified the railway crossing and track area.$$,
      $$Whether the system recognised the need to maintain sufficient downstream clearance before entering the crossing.$$,
      $$Whether queueing, traffic signals, road geometry or route planning contributed.$$,
      $$Whether the vehicle would actually have stopped within the railway-track area without intervention.$$,
      $$The exact remaining distance and safety margin at the moment of intervention.$$
    ],
    $$The event is consistent with inadequate anticipation of a railway-crossing clearance constraint. The driver intervened forcefully because of concern that the vehicle could become stopped within or too close to the track area. The available video documents the trajectory and the intervention but cannot establish the internal cause or what the system would ultimately have done without intervention.$$,
    $$undetermined$$, null, $$curator-reviewed$$, $$2026-08-30$$
  )

)
insert into event (
  slug, title, summary, occurred_on, occurred_on_precision,
  location_text, location_country_code, developer_or_operator, system_name,
  automation_status, system_version, system_version_knowledge,
  event_type, valence, observed_facts, unknowns, interpretation,
  causation_status, causation_note, review_status, record_updated
)
select
  slug, title, summary, occurred_on::date, occurred_on_precision,
  location_text, location_country_code, developer_or_operator, system_name,
  automation_status, system_version, system_version_knowledge,
  event_type, valence, observed_facts::text[], unknowns::text[], interpretation,
  causation_status, causation_note, review_status, record_updated::date
from seed
on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  occurred_on = excluded.occurred_on,
  occurred_on_precision = excluded.occurred_on_precision,
  location_text = excluded.location_text,
  location_country_code = excluded.location_country_code,
  developer_or_operator = excluded.developer_or_operator,
  system_name = excluded.system_name,
  automation_status = excluded.automation_status,
  system_version = excluded.system_version,
  system_version_knowledge = excluded.system_version_knowledge,
  event_type = excluded.event_type,
  valence = excluded.valence,
  observed_facts = excluded.observed_facts,
  unknowns = excluded.unknowns,
  interpretation = excluded.interpretation,
  causation_status = excluded.causation_status,
  causation_note = excluded.causation_note,
  review_status = excluded.review_status,
  record_updated = excluded.record_updated
where
  event.title is distinct from excluded.title
  or event.summary is distinct from excluded.summary
  or event.occurred_on is distinct from excluded.occurred_on
  or event.occurred_on_precision is distinct from excluded.occurred_on_precision
  or event.location_text is distinct from excluded.location_text
  or event.location_country_code is distinct from excluded.location_country_code
  or event.developer_or_operator is distinct from excluded.developer_or_operator
  or event.system_name is distinct from excluded.system_name
  or event.automation_status is distinct from excluded.automation_status
  or event.system_version is distinct from excluded.system_version
  or event.system_version_knowledge is distinct from excluded.system_version_knowledge
  or event.event_type is distinct from excluded.event_type
  or event.valence is distinct from excluded.valence
  or event.observed_facts is distinct from excluded.observed_facts
  or event.unknowns is distinct from excluded.unknowns
  or event.interpretation is distinct from excluded.interpretation
  or event.causation_status is distinct from excluded.causation_status
  or event.causation_note is distinct from excluded.causation_note
  or event.review_status is distinct from excluded.review_status
  or event.record_updated is distinct from excluded.record_updated;

-- ---------------------------------------------------------------------------
-- event_source (one source per event; joined to its parent event by slug)
-- ---------------------------------------------------------------------------
with seed_source (
  event_slug, url, source_type, publisher, label,
  published_on, published_on_precision, retrieved_on, note
) as (
  values

  -- 1. fsd-slows-for-crossing-pedestrian-then-resumes
  (
    $$fsd-slows-for-crossing-pedestrian-then-resumes$$,
    $$https://youtube.com/shorts/iiJl2ww45aY?feature=share$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing FSD responding to a crossing pedestrian$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing the vehicle slowing for a crossing pedestrian and resuming after the pedestrian halts.$$
  ),

  -- 2. fsd-remains-stopped-in-car-park-then-hesitates
  (
    $$fsd-remains-stopped-in-car-park-then-hesitates$$,
    $$https://x.com/WhiteBoxAV/status/2093803233139728746$$,
    $$x-post$$, $$White Box Autonomy$$,
    $$White Box Autonomy video and description of the car-park interaction$$,
    null, $$unknown$$, null,
    $$White Box Autonomy post describing a car-park sequence in which the vehicle holds position as another car passes, then hesitates in a right-of-way interaction.$$
  ),

  -- 3. fsd-repeated-lateral-weaving
  (
    $$fsd-repeated-lateral-weaving$$,
    $$https://www.youtube.com/shorts/uSmZPUCrr0M$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing repeated lateral weaving$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing repeated side-to-side movement during automated driving.$$
  ),

  -- 4. fsd-right-turn-from-left-turn-only-lane
  (
    $$fsd-right-turn-from-left-turn-only-lane$$,
    $$https://www.youtube.com/shorts/GTKoK3bY-TM$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing an attempted right turn from a left-turn-only lane$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing an attempted right turn from a left-turn-only lane, ended by driver intervention.$$
  ),

  -- 5. fsd-does-not-yield-to-ambulance-before-intervention
  (
    $$fsd-does-not-yield-to-ambulance-before-intervention$$,
    $$https://youtube.com/shorts/caOYqojUWdM?feature=share$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing an ambulance interaction requiring driver intervention$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing an ambulance interaction in which the driver takes over.$$
  ),

  -- 6. fsd-course-change-within-intersection
  (
    $$fsd-course-change-within-intersection$$,
    $$https://youtube.com/shorts/fxLCDR3mOt8?feature=share$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing an unexpected trajectory change within an intersection$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing a mid-intersection change of course toward a red-signalled direction.$$
  ),

  -- 7. fsd-road-markings-low-traffic-street
  (
    $$fsd-road-markings-low-traffic-street$$,
    $$https://youtube.com/shorts/v18m9_GyajQ?feature=share$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing inappropriate path selection relative to road markings$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing path selection inconsistent with road markings on a near-empty street at night.$$
  ),

  -- 8. fsd-standing-water-stormy-night
  (
    $$fsd-standing-water-stormy-night$$,
    $$https://youtube.com/shorts/9RJMaLhc0B0?feature=share$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing FSD entering substantial standing water during stormy nighttime conditions$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing the vehicle driving through a large area of standing water at night.$$
  ),

  -- 9. fsd-railway-crossing-hard-braking
  (
    $$fsd-railway-crossing-hard-braking$$,
    $$https://youtube.com/shorts/GK_oaQXsOVw?feature=share$$,
    $$youtube-video$$, $$White Box Autonomy$$,
    $$White Box Autonomy video showing a railway-crossing event requiring hard braking intervention$$,
    null, $$unknown$$, null,
    $$First-person clip recorded by White Box Autonomy showing a railway-crossing approach that ends with a hard braking intervention.$$
  )

)
insert into event_source (
  event_id, url, source_type, publisher, label,
  published_on, published_on_precision, retrieved_on, note
)
select
  e.id, s.url, s.source_type, s.publisher, s.label,
  s.published_on::date, s.published_on_precision, s.retrieved_on::date, s.note
from seed_source s
join event e on e.slug = s.event_slug
on conflict (event_id, url) do update set
  source_type = excluded.source_type,
  publisher = excluded.publisher,
  label = excluded.label,
  published_on = excluded.published_on,
  published_on_precision = excluded.published_on_precision,
  retrieved_on = excluded.retrieved_on,
  note = excluded.note
where
  event_source.source_type is distinct from excluded.source_type
  or event_source.publisher is distinct from excluded.publisher
  or event_source.label is distinct from excluded.label
  or event_source.published_on is distinct from excluded.published_on
  or event_source.published_on_precision is distinct from excluded.published_on_precision
  or event_source.retrieved_on is distinct from excluded.retrieved_on
  or event_source.note is distinct from excluded.note;

-- ---------------------------------------------------------------------------
-- publish — the ONLY path to is_public = true, for every caller including this
-- seed. Runs after the sources above exist, so the database invariant
-- "a public event has >= 1 source" holds. Idempotent: once the records are
-- public the WHERE matches nothing and first_published_at is never re-stamped.
-- ---------------------------------------------------------------------------
update event
   set is_public = true
 where slug in (
   'fsd-slows-for-crossing-pedestrian-then-resumes',
   'fsd-remains-stopped-in-car-park-then-hesitates',
   'fsd-repeated-lateral-weaving',
   'fsd-right-turn-from-left-turn-only-lane',
   'fsd-does-not-yield-to-ambulance-before-intervention',
   'fsd-course-change-within-intersection',
   'fsd-road-markings-low-traffic-street',
   'fsd-standing-water-stormy-night',
   'fsd-railway-crossing-hard-braking'
 )
   and is_public is not true;

commit;
