import type { Event } from "../types";

/**
 * Seed dataset for the Observatory.
 *
 * These are REAL first-person observations documented by White Box Autonomy
 * while using Tesla FSD (Supervised). Each record is editorial metadata derived
 * from a primary source video or post: the linked source is the evidence, this
 * text is not.
 *
 * Editorial rules applied to every record (see /methodology and CLAUDE.md):
 *  - directly observable behaviour is recorded as fact; internal perception,
 *    prediction, planning or intent is NOT asserted unless the evidence
 *    establishes it;
 *  - `automationStatus` and `causation` are independent — engagement of the
 *    driving-automation system does not by itself establish that it caused the
 *    behaviour;
 *  - `causation.status` stays "undetermined" unless a source supports more;
 *  - unknown dates, locations, software versions and mechanisms are left
 *    explicitly unknown, never guessed; publication dates of source videos are
 *    not used as event dates;
 *  - `recordUpdated` is the date this record was created or materially reviewed,
 *    not the event date.
 *
 * Load-time invariants (enforced in ../local-source.ts): unique slug; at least
 * one observedFacts entry and one source; a recordUpdated date. `unknowns` may
 * legitimately be empty (it happens not to be, for any record below), but is
 * not required.
 */

const RECORD_UPDATED = "2026-08-30";

export const seedEvents: Event[] = [
  {
    slug: "fsd-slows-for-crossing-pedestrian-then-resumes",
    title:
      "FSD slows for a crossing pedestrian, then resumes as the pedestrian stops",
    summary:
      "With FSD (Supervised) engaged, the vehicle slowed as a pedestrian ran across its path and resumed acceleration shortly after the pedestrian stopped part-way across.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "vulnerable-road-user-interaction",
    valence: "successful-handling",
    observedFacts: [
      "FSD (Supervised) was engaged during the interaction.",
      "A pedestrian ran across the vehicle's path.",
      "The vehicle slowed while the pedestrian was crossing.",
      "The pedestrian stopped before completing the crossing.",
      "The vehicle resumed acceleration shortly after the pedestrian stopped.",
      "No collision occurred in the recorded interaction.",
    ],
    unknowns: [
      "What cues the automation used in responding to the pedestrian.",
      "Whether the system predicted that the pedestrian would stop, or reacted after detecting the reduction in pedestrian movement.",
      "The internal pedestrian trajectory or prediction generated by the system.",
    ],
    interpretation:
      "The rapid transition from yielding to resuming movement is consistent with an effective response to the pedestrian's changing behaviour. The external video evidence alone cannot establish whether the system anticipated the pedestrian's intention or reacted after detecting the pedestrian stopping.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://youtube.com/shorts/iiJl2ww45aY?feature=share",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label:
          "White Box Autonomy video showing FSD responding to a crossing pedestrian",
        note: "First-person clip recorded by White Box Autonomy showing the vehicle slowing for a crossing pedestrian and resuming after the pedestrian halts.",
      },
    ],
  },
  {
    slug: "fsd-remains-stopped-in-car-park-then-hesitates",
    title:
      "FSD remains stopped as another vehicle passes in a car park, then hesitates during a right-of-way interaction",
    summary:
      "With FSD (Supervised) engaged in a busy car park, the vehicle stayed stopped while another vehicle passed through the area ahead of its intended path. Shortly afterwards it hesitated during an interaction with an oncoming vehicle that was indicating a turn, and the other driver waved it through.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "unexpected-or-inappropriate-behaviour",
    valence: "neutral-or-unclear",
    observedFacts: [
      "FSD (Supervised) was activated in a busy car park.",
      "The vehicle initially did not proceed with the intended manoeuvre.",
      "Another vehicle passed through the area ahead of the vehicle's intended path.",
      "The vehicle remained stationary while that other vehicle passed.",
      "Shortly afterwards the vehicle stopped or hesitated during an interaction with an oncoming vehicle that was indicating a right turn.",
      "The other driver then used a hand gesture indicating that the vehicle could proceed.",
    ],
    unknowns: [
      "Which objects or predicted trajectories caused the initial stationary behaviour.",
      "Whether the passing vehicle was the primary reason the system did not proceed.",
      "Why the system hesitated during the second interaction.",
      "How the system interpreted the other vehicle's indicator.",
      "Whether or how the hand gesture influenced subsequent behaviour.",
      "Whether the system explicitly represented right of way.",
    ],
    interpretation:
      "The first interaction is consistent with cautious and potentially beneficial conflict avoidance: proceeding could have created a conflict with the passing vehicle. The second interaction suggests greater difficulty resolving an ambiguous social negotiation involving an indicator, right of way and a driver's hand gesture. The available external evidence does not reveal the system's internal reasoning.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://x.com/WhiteBoxAV/status/2093803233139728746",
        type: "x-post",
        publisher: "White Box Autonomy",
        label: "White Box Autonomy video and description of the car-park interaction",
        note: "White Box Autonomy post describing a car-park sequence in which the vehicle holds position as another car passes, then hesitates in a right-of-way interaction.",
      },
    ],
  },
  {
    slug: "fsd-repeated-lateral-weaving",
    title: "FSD exhibits repeated lateral weaving during automated driving",
    summary:
      "On the first day of using a newly updated version of Tesla FSD (Supervised), with automation engaged, the vehicle moved from side to side repeatedly over a short period in a way inconsistent with holding a stable path.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "near-miss-or-safety-critical",
    valence: "failure-or-challenging",
    observedFacts: [
      "The event occurred during the first day of using a newly updated version of Tesla FSD (Supervised).",
      "Driving automation was engaged.",
      "The vehicle moved laterally from side to side.",
      "The lateral movement repeated during a short period.",
      "The behaviour was inconsistent with maintaining a stable roadway path.",
      "No collision occurred in the recorded event.",
    ],
    unknowns: [
      "The perception, localisation, planning or control process associated with the oscillation.",
      "Whether road geometry, lane markings, localisation, surrounding traffic or other environmental conditions contributed.",
      "Whether the behaviour would have continued without intervention.",
      "The exact lateral displacement and safety margin.",
      "The exact software version in use.",
    ],
    interpretation:
      "The repeated lateral movement is consistent with unstable or inappropriate path control during automated driving. The available video can document the observable weaving, but it cannot establish which subsystem or environmental factor caused the behaviour.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://www.youtube.com/shorts/uSmZPUCrr0M",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label: "White Box Autonomy video showing repeated lateral weaving",
        note: "First-person clip recorded by White Box Autonomy showing repeated side-to-side movement during automated driving.",
      },
    ],
  },
  {
    slug: "fsd-right-turn-from-left-turn-only-lane",
    title: "FSD attempts a right turn from a left-turn-only lane",
    summary:
      "With FSD (Supervised) engaged while the vehicle was in a lane marked for left turns only, the system began a right-turn manoeuvre from that lane while traffic was moving in the target direction. The driver intervened before the manoeuvre was completed.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "traffic-rule-or-infrastructure-interpretation",
    valence: "failure-or-challenging",
    observedFacts: [
      "The vehicle was travelling in a lane designated for left turns only.",
      "With FSD (Supervised) engaged, the vehicle initiated or attempted a right-turn manoeuvre from that lane.",
      "Moving traffic was present in the direction of the attempted manoeuvre.",
      "The driver intervened before the manoeuvre was completed.",
      "No collision occurred.",
    ],
    unknowns: [
      "Whether the lane-use restriction was perceived correctly.",
      "Whether road geometry, map information, lane markings or route guidance contributed.",
      "Whether the intended navigation route required a right turn.",
      "The exact time-to-collision or remaining safety margin.",
      "What trajectory the vehicle would ultimately have followed without intervention.",
    ],
    interpretation:
      "The event is consistent with an inappropriate manoeuvre selection relative to the marked lane-use restriction. The intervention prevented the attempted turn from progressing into moving traffic. The available video does not establish whether the underlying cause involved lane perception, map interpretation, route planning or another component of the driving-automation system.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://www.youtube.com/shorts/GTKoK3bY-TM",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label:
          "White Box Autonomy video showing an attempted right turn from a left-turn-only lane",
        note: "First-person clip recorded by White Box Autonomy showing an attempted right turn from a left-turn-only lane, ended by driver intervention.",
      },
    ],
  },
  {
    slug: "fsd-does-not-yield-to-ambulance-before-intervention",
    title: "FSD does not yield to an ambulance before driver intervention",
    summary:
      "With FSD (Supervised) engaged, the vehicle did not perform the yielding response the driver judged necessary while an ambulance was present in surrounding traffic, and the driver took over control.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "emergency-vehicle-interaction",
    valence: "failure-or-challenging",
    observedFacts: [
      "An ambulance was present in the surrounding traffic environment.",
      "FSD (Supervised) was engaged during the interaction.",
      "Before driver intervention, the vehicle did not exhibit the yielding response the driver considered necessary.",
      "The driver intervened and took control.",
      "No collision occurred.",
    ],
    unknowns: [
      "Whether the system detected and correctly classified the ambulance.",
      "Whether emergency lights or a siren were active and clearly detectable from the evidence.",
      "Whether the system recognised a requirement to yield.",
      "What trajectory or behavioural prediction the system generated for the ambulance.",
      "Whether the system would eventually have yielded without intervention.",
    ],
    interpretation:
      "The event is consistent with an inadequate response to an emergency vehicle while driving automation was engaged. The available evidence establishes the externally observable behaviour and the driver intervention, but does not determine whether the limitation arose from perception, classification, behavioural prediction, right-of-way reasoning or motion planning.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://youtube.com/shorts/caOYqojUWdM?feature=share",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label:
          "White Box Autonomy video showing an ambulance interaction requiring driver intervention",
        note: "First-person clip recorded by White Box Autonomy showing an ambulance interaction in which the driver takes over.",
      },
    ],
  },
  {
    slug: "fsd-course-change-within-intersection",
    title: "FSD changes course within an intersection toward a red signal",
    summary:
      "While traversing an intersection with FSD (Supervised) engaged, the vehicle changed its path or heading, and the revised trajectory moved toward a direction associated with a red traffic signal so far as the recording shows.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "traffic-rule-or-infrastructure-interpretation",
    valence: "failure-or-challenging",
    observedFacts: [
      "The vehicle entered or was travelling through an intersection with FSD (Supervised) engaged.",
      "While within the intersection, the vehicle changed its path or heading.",
      "The revised trajectory took the vehicle toward a movement associated with a red traffic signal, so far as is clearly visible from the evidence.",
      "The behaviour prompted driver concern.",
      "No collision occurred in the recorded event.",
    ],
    unknowns: [
      "Whether lane geometry, turn-path interpretation, lane assignment, route guidance or traffic-signal association contributed.",
      "Whether the visible red signal definitively applied to the trajectory the system was attempting to follow.",
      "The path the vehicle would ultimately have followed without intervention.",
      "Whether map data, perception, localisation or planning contributed.",
      "Whether and when the driver intervened.",
    ],
    interpretation:
      "The event is consistent with an inappropriate change in planned trajectory while traversing an intersection. The resulting path appeared to align with a movement controlled by a red signal. The available external evidence does not reveal whether the underlying issue arose from lane interpretation, signal association, localisation, route planning or another component.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://youtube.com/shorts/fxLCDR3mOt8?feature=share",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label:
          "White Box Autonomy video showing an unexpected trajectory change within an intersection",
        note: "First-person clip recorded by White Box Autonomy showing a mid-intersection change of course toward a red-signalled direction.",
      },
    ],
  },
  {
    slug: "fsd-road-markings-low-traffic-street",
    title: "FSD does not follow road markings on a low-traffic street",
    summary:
      "At around 4 a.m. on a street with little or no visible traffic, with FSD (Supervised) engaged, the vehicle's path did not consistently follow the visible road markings and lane layout.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "traffic-rule-or-infrastructure-interpretation",
    valence: "failure-or-challenging",
    observedFacts: [
      "The event occurred at approximately 4 a.m.",
      "Traffic was very light or absent in the visible scene.",
      "Road markings were present.",
      "With FSD (Supervised) engaged, the vehicle did not consistently follow the marked roadway or lane guidance.",
      "The vehicle's path was inconsistent with the expected movement indicated by the visible road markings and traffic-control layout.",
      "No collision occurred.",
    ],
    unknowns: [
      "Whether the road markings were perceived correctly.",
      "Whether map information or route guidance conflicted with the physical road layout.",
      "Whether lighting, road-surface condition or marking quality influenced the behaviour.",
      "Whether perception, localisation, planning or another component contributed.",
      "Whether the same behaviour would occur during daylight or in heavier traffic.",
      "Which specific road rules, if any, were breached.",
    ],
    interpretation:
      "The event is consistent with a failure to interpret or comply with visible roadway guidance in a low-traffic environment. The relatively simple surrounding traffic conditions make the behaviour noteworthy, but the external video alone cannot establish why the system selected that path.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://youtube.com/shorts/v18m9_GyajQ?feature=share",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label:
          "White Box Autonomy video showing inappropriate path selection relative to road markings",
        note: "First-person clip recorded by White Box Autonomy showing path selection inconsistent with road markings on a near-empty street at night.",
      },
    ],
  },
  {
    slug: "fsd-standing-water-stormy-night",
    title:
      "FSD drives through substantial standing water at night in stormy conditions",
    summary:
      "At night in stormy conditions, with FSD (Supervised) engaged, the vehicle continued into a large area of standing water on the roadway and produced a substantial splash while passing through it.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "unexpected-or-inappropriate-behaviour",
    valence: "failure-or-challenging",
    observedFacts: [
      "The event occurred at night during stormy or heavy-rain conditions.",
      "A substantial area of standing water was visible on the roadway.",
      "With FSD (Supervised) engaged, the vehicle continued into the standing water.",
      "The vehicle produced a substantial splash while passing through it.",
      "No collision occurred in the recorded event.",
    ],
    unknowns: [
      "The depth of the standing water.",
      "Whether the system detected the water as a distinct roadway hazard.",
      "Whether the vehicle modified its speed before entering the water.",
      "Whether the roadway remained safely passable.",
      "Whether visibility, reflections, rainfall or sensor performance influenced the behaviour.",
      "What the system would have done if the water had been deeper or impassable.",
    ],
    interpretation:
      "The event shows the driving-automation system proceeding through substantial standing water under degraded nighttime weather conditions. The available video establishes the observable vehicle behaviour, but not whether the system recognised the water as a hazard or how it assessed its depth and passability.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://youtube.com/shorts/9RJMaLhc0B0?feature=share",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label:
          "White Box Autonomy video showing FSD entering substantial standing water during stormy nighttime conditions",
        note: "First-person clip recorded by White Box Autonomy showing the vehicle driving through a large area of standing water at night.",
      },
    ],
  },
  {
    slug: "fsd-railway-crossing-hard-braking",
    title:
      "FSD proceeds toward a railway crossing before a hard braking intervention",
    summary:
      "With FSD (Supervised) engaged, the vehicle continued forward in a railway-crossing environment to a point where track clearance became a concern to the driver, who applied a hard braking input strong enough to displace unsecured objects in the vehicle.",
    occurredOn: { value: "", precision: "unknown" },
    developerOrOperator: "Tesla",
    systemName: "FSD (Supervised)",
    automationStatus: "driving-automation-engaged-confirmed",
    systemVersion: { knowledge: "unknown" },
    eventType: "traffic-rule-or-infrastructure-interpretation",
    valence: "failure-or-challenging",
    observedFacts: [
      "The vehicle approached or entered a railway-crossing environment with FSD (Supervised) engaged.",
      "The vehicle continued forward into a situation where railway-track clearance became a concern to the driver.",
      "The driver applied a hard braking intervention.",
      "The braking was forceful enough that unsecured objects inside the vehicle moved substantially.",
      "No collision occurred.",
    ],
    unknowns: [
      "Whether the system correctly identified the railway crossing and track area.",
      "Whether the system recognised the need to maintain sufficient downstream clearance before entering the crossing.",
      "Whether queueing, traffic signals, road geometry or route planning contributed.",
      "Whether the vehicle would actually have stopped within the railway-track area without intervention.",
      "The exact remaining distance and safety margin at the moment of intervention.",
    ],
    interpretation:
      "The event is consistent with inadequate anticipation of a railway-crossing clearance constraint. The driver intervened forcefully because of concern that the vehicle could become stopped within or too close to the track area. The available video documents the trajectory and the intervention but cannot establish the internal cause or what the system would ultimately have done without intervention.",
    causation: { status: "undetermined" },
    reviewStatus: "curator-reviewed",
    origin: "curated",
    recordUpdated: RECORD_UPDATED,
    sources: [
      {
        url: "https://youtube.com/shorts/GK_oaQXsOVw?feature=share",
        type: "youtube-video",
        publisher: "White Box Autonomy",
        label:
          "White Box Autonomy video showing a railway-crossing event requiring hard braking intervention",
        note: "First-person clip recorded by White Box Autonomy showing a railway-crossing approach that ends with a hard braking intervention.",
      },
    ],
  },
];
